package wasm-ecosystem:dwarf;

 
interface dwarf-parser {
  resource dwo {
    constructor(obj-binary: list<u8>);
    get-line-map: func() -> string; // [{ line: number, address: number }]
    list-cu: func() -> string; // [{name: string}]
    list-subprograms: func(cu: string) -> string; // [{cu:string, name: string, high_pc: number, low_pc: number}]
  }
}

world dwarf {
  export dwarf-parser;
}